### ISSUE TITLE
Google Dumb

### ISSUE THREAD

**Issue by SyntagmaX** [razeghi71/obsidian-image-search#1]
I really liked the tool, it will be very useful for the annotation flow. The only issue is that when I get to the API generation page, Google opens a pop-up and keeps loading and nothing happens. I've tried in another browser and I'm not getting it.

**Comment by razeghi71** [comment]
Hi @n30s4m, Thanks for the first issue here :D

Is the issue still present? can you please elaborate more which page are you referring to? also screenshots are appreciated.

**Comment by samxyzbr** [comment]
Hello my friend, firstly, congratulations on having developed something so useful and secondly, I managed to resolve the API issue by generating a payment within Google Cloud (maybe that was what Google really wanted from me) despite them having given me a lot of credits. 

I have been using your plugin to search for images, making the flow easier, without the need to open a browser (even the ones that exist for Obsidian), copy images or cut. Perhaps the image selection window could be a little larger, to show larger thumbnails. For example: I study for public exams in Brazil and there is a lot of content in images of diagrams, mind maps, but as the thumbnails are small, I rely a little on intuition when choosing. In any case, congratulations. Success, today, tomorrow and always.

**Comment by razeghi71** [comment]
Thank you @n30s4m for your kind words,

The payment that you added probably has an effect, I think it's not working until you add your credit card in the billing, even if you have 300 free usage. Thank you for that, I'll try to add it in the getting started guide.

Also about the feature you requested, they really make great sense, I'll try to implement an initial version out of it this week and release it and get your feedback. Thanks!

**Comment by razeghi71** [comment]
Thanks again.

Made an issue to address it in https://github.com/razeghi71/obsidian-image-search/issues/3
