### ISSUE TITLE
[Doc] could you add a blurb in the README about privacy

### ISSUE THREAD

**Issue by huyz** [razeghi71/obsidian-image-search#2]
Are all our images in our Vault sent to Google?

**Comment by razeghi71** [comment]
Hi @huyz 
Can you please elaborate a little about what do you mean by "sent to google"?

**Comment by huyz** [comment]
Sorry, I completely misunderstood what this plugin was for. I thought it was for searching one's own images (hopefully after they were OCR'd).

This is still useful plugin :)
