### ISSUE TITLE
[Feat] support hitting Enter key after typing search string

### ISSUE THREAD

**Issue by huyz** [razeghi71/obsidian-image-search#4]
Right now I just hit Enter and it takes me a while to realize that i have to click on the Search button.

(Also, could you make the input field a bit wider?)

Thanks

**Comment by razeghi71** [comment]
Hi @huyz,

sure thing. I'll work on it whenever I had time.

**Comment by razeghi71** [comment]
Thanks @huyz for your suggestion

I made #5 and #6 based on your request, will work on as soon as I had time. I will close this Issue and track this features there.
